name: frontend
description: frontend for game.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter_svg: ^2.0.6
  http: ^1.0.0
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  get_it: ^7.2.0
  intl: ^0.17.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true